// <auto-generated />
using System;
using DefinitiveEdition.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DefinitiveEdition.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200821011605_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.ConsoleDeveloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsoleDeveloper");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nintendo"
                        });
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.FeatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeatureType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pro"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Neutral"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Con"
                        });
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InitialReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccf277b7-b189-448a-9468-70105aaa7fc8"),
                            InitialReleaseDate = new DateTime(2000, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Legend of Zelda - Majora's Mask",
                            SeriesId = new Guid("1af5b35c-4c32-4a5d-ab3a-daeb5ec78e21")
                        });
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.GameConsole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsoleDeveloperId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitialReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleDeveloperId");

                    b.ToTable("GameConsole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fc6465c-c8c4-4496-9040-d5faa7ce71a2"),
                            ConsoleDeveloperId = 1,
                            InitialReleaseDate = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "64"
                        },
                        new
                        {
                            Id = new Guid("e6ac0412-b8d0-43ce-8d3a-b3d80f70db75"),
                            ConsoleDeveloperId = 1,
                            InitialReleaseDate = new DateTime(2011, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "3DS"
                        });
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.GamePort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameConsoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInitialRelease")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSameName")
                        .HasColumnType("bit");

                    b.Property<string>("PortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameConsoleId");

                    b.HasIndex("GameId");

                    b.ToTable("GamePort");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdb1993e-bca6-4961-9426-18a8f680c730"),
                            GameConsoleId = new Guid("9fc6465c-c8c4-4496-9040-d5faa7ce71a2"),
                            GameId = new Guid("ccf277b7-b189-448a-9468-70105aaa7fc8"),
                            IsInitialRelease = true,
                            IsSameName = true
                        },
                        new
                        {
                            Id = new Guid("ef2d234e-e70f-400b-850a-2d460129e563"),
                            GameConsoleId = new Guid("e6ac0412-b8d0-43ce-8d3a-b3d80f70db75"),
                            GameId = new Guid("ccf277b7-b189-448a-9468-70105aaa7fc8"),
                            IsInitialRelease = false,
                            IsSameName = false,
                            PortName = "The Legend of Zelda - Majora's Mask 3D",
                            ReleaseDate = new DateTime(2015, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.PortFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeatureTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("GamePortId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FeatureTypeId");

                    b.HasIndex("GamePortId");

                    b.ToTable("PortFeature");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbb679fc-0941-4b76-b596-7c12420c4896"),
                            Description = "Swimming speed while wearing the Zora mask is automatically fast without needing to use magic",
                            Feature = "Fast Zora Swimming",
                            FeatureTypeId = 1,
                            GamePortId = new Guid("fdb1993e-bca6-4961-9426-18a8f680c730")
                        },
                        new
                        {
                            Id = new Guid("5fd825af-56cf-4343-81ee-f4372f2c38a1"),
                            Description = "The original release of Majora's Mask capped out at a framerate of 20 FPS. Little hard on the eyes at first",
                            Feature = "20 FPS",
                            FeatureTypeId = 3,
                            GamePortId = new Guid("fdb1993e-bca6-4961-9426-18a8f680c730")
                        },
                        new
                        {
                            Id = new Guid("0c66e103-39d1-4c84-87d8-7cb71d597ada"),
                            Description = "The 3DS port runs a bit smoother at 30 FPS, which is easier on the eyes",
                            Feature = "30 FPS",
                            FeatureTypeId = 1,
                            GamePortId = new Guid("ef2d234e-e70f-400b-850a-2d460129e563")
                        },
                        new
                        {
                            Id = new Guid("7b46ba9c-52e2-4ec8-a971-14e7bb8c22f7"),
                            Description = "Some purists may complain that this takes away from the original, the Song of Double Time can take you to a specific time of the current day you are on.",
                            Feature = "Improved Song of Double Time",
                            FeatureTypeId = 2,
                            GamePortId = new Guid("ef2d234e-e70f-400b-850a-2d460129e563")
                        },
                        new
                        {
                            Id = new Guid("e43a0874-843f-4a7b-a5b8-62aa06cb7770"),
                            Description = "Without using Magic, the Zora swimming speed will seem like you are crawling through the ocean. Fan patches have been made to patch this though",
                            Feature = "Slow Zora Swimming",
                            FeatureTypeId = 3,
                            GamePortId = new Guid("ef2d234e-e70f-400b-850a-2d460129e563")
                        });
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InitialReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1af5b35c-4c32-4a5d-ab3a-daeb5ec78e21"),
                            Description = "Save the Princess and Hyrule from Ganon sometimes. Fix me up later....",
                            InitialReleaseDate = new DateTime(1986, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Legend of Zelda"
                        });
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.Game", b =>
                {
                    b.HasOne("DefinitiveEdition.Api.Data.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.GameConsole", b =>
                {
                    b.HasOne("DefinitiveEdition.Api.Data.Models.ConsoleDeveloper", "ConsoleDeveloper")
                        .WithMany()
                        .HasForeignKey("ConsoleDeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.GamePort", b =>
                {
                    b.HasOne("DefinitiveEdition.Api.Data.Models.GameConsole", "GameConsole")
                        .WithMany()
                        .HasForeignKey("GameConsoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DefinitiveEdition.Api.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefinitiveEdition.Api.Data.Models.PortFeature", b =>
                {
                    b.HasOne("DefinitiveEdition.Api.Data.Models.FeatureType", "FeatureType")
                        .WithMany()
                        .HasForeignKey("FeatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DefinitiveEdition.Api.Data.Models.GamePort", "GamePort")
                        .WithMany()
                        .HasForeignKey("GamePortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
